### PR TITLE
Update recursive_GCD.c

### PR DESCRIPTION
**Pull request by BishalK007**
braces in switch cases needed

### CODE REVIEW

**Review by arnab7070 — COMMENTED** [review]
Case does not need a bracket.

**Comment by BishalK007** [comment]
image
It needs when variables are declared inside cases.

**Comment by arnab7070** [comment]
Screenshot (32)
See, in my VS Code it doesn't create any type of problem. Ok as it's not working for your case I am updating the file. Thank You.

**Comment by BishalK007** [comment]
ok👍👍

**Pull request merged**
